### ISSUE TITLE
Punycode is deprecated

### ISSUE THREAD

**Issue by Smorci** [MinaFoundation/PGT_gptSurveySummarizer#23]
When running both of the applications we get a DepracationWarning

`summarizer-1  | (node:19) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.`
`bot-1         | (node:19) [DEP0040] DeprecationWarning: The punycode module is deprecated. Please use a userland alternative instead.`

**Comment by johnmarcou** [comment]
Yes, this is caused by https://github.com/openai/openai-node library.

There is an issue about it here: https://github.com/openai/openai-node/issues/780. This should be fixed in the next updated of the library: https://github.com/openai/openai-node/pull/402#issuecomment-2016678933.

**Comment by MadGeometer** [comment]
Is there an ETA for fixing the Punycode issue? This is still happening with
nodejs version = v21.7.3
"openai": "^4.60.0"
