### ISSUE TITLE
(Production environment) Issues with the Survey Summaries: bot is leaving a trail of messages instead of overwriting the summary.

### ISSUE THREAD

**Issue by CristinaEche** [MinaFoundation/PGT_gptSurveySummarizer#75]
@berkingurcan 

When using the auto-post command, the bot is not overwriting the full Survey Summary, and is leaving a trail of text:

<img width="906" alt="image" src="https://github.com/user-attachments/assets/f34a7c66-a2eb-4c7b-b516-316830309e91">

![image](https://github.com/user-attachments/assets/09e6216d-d596-4039-8b24-e1cc1052d94a)

Here is the thread: https://discord.com/channels/484437221055922177/1280888811798270054 

We need the bot to delete old summaries and keep the latest ones. 

CC: @es92 @remigiusz-antczak

**Comment by berkingurcan** [comment]
Do we encounter this problem in staging?
If not, bot basically has no permission to delete messages. And also, can you send the logs when this happened?

**Comment by CristinaEche** [comment]
@berkingurcan 

Hi, It has the option of deleting messages activated:

<img width="559" alt="image" src="https://github.com/user-attachments/assets/3945070a-216d-4daf-afd0-1f7ae6e058f7">


Here are the Logs from yesterday:


2024-09-16T00:05:00.001Z INFO: Starting auto posting |  
-- | --
  |   | 2024-09-16T00:05:00.002Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T00:05:00.182Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T00:05:00.182Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T00:05:01.443Z INFO: 59.97595 minutes until the next auto-posting |  
  |   | 2024-09-16T01:05:00.002Z INFO: Starting auto posting |  
  |   | 2024-09-16T01:05:00.002Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T01:05:00.173Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T01:05:00.173Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T01:05:01.129Z INFO: 59.981183333333334 minutes until the next auto-posting |  
  |   | 2024-09-16T02:05:00.006Z INFO: Starting auto posting |  
  |   | 2024-09-16T02:05:00.007Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T02:05:00.214Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T02:05:00.214Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T02:05:01.135Z INFO: 59.98108333333333 minutes until the next auto-posting |  
  |   | 2024-09-16T03:05:00.015Z INFO: Starting auto posting |  
  |   | 2024-09-16T03:05:00.016Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T03:05:00.247Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T03:05:00.247Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T03:05:01.490Z INFO: 59.975166666666674 minutes until the next auto-posting |  
  |   | 2024-09-16T04:05:00.023Z INFO: Starting auto posting |  
  |   | 2024-09-16T04:05:00.024Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T04:05:00.216Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T04:05:00.217Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T04:05:01.208Z INFO: 59.979866666666666 minutes until the next auto-posting |  
  |   | 2024-09-16T05:05:00.007Z INFO: Starting auto posting |  
  |   | 2024-09-16T05:05:00.008Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T05:05:00.162Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T05:05:00.162Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T05:05:01.142Z INFO: 59.98096666666667 minutes until the next auto-posting |  
  |   | 2024-09-16T06:05:00.015Z INFO: Starting auto posting |  
  |   | 2024-09-16T06:05:00.016Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T06:05:00.186Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T06:05:00.186Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T06:05:01.401Z INFO: 59.97665 minutes until the next auto-posting |  
  |   | 2024-09-16T07:05:00.007Z INFO: Starting auto posting |  
  |   | 2024-09-16T07:05:00.008Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T07:05:00.178Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T07:05:00.178Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T07:05:01.061Z INFO: 59.98231666666666 minutes until the next auto-posting |  
  |   | 2024-09-16T08:05:00.015Z INFO: Starting auto posting |  
  |   | 2024-09-16T08:05:00.016Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T08:05:00.214Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T08:05:00.214Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T08:05:01.283Z INFO: 59.97861666666667 minutes until the next auto-posting |  
  |   | 2024-09-16T09:05:00.026Z INFO: Starting auto posting |  
  |   | 2024-09-16T09:05:00.027Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T09:05:00.199Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T09:05:00.200Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T09:05:01.198Z INFO: 59.98003333333334 minutes until the next auto-posting |  
  |   | 2024-09-16T10:05:00.003Z INFO: Starting auto posting |  
  |   | 2024-09-16T10:05:00.004Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T10:05:00.178Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T10:05:00.178Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T10:05:01.161Z INFO: 59.98065 minutes until the next auto-posting |  
  |   | 2024-09-16T11:05:00.003Z INFO: Starting auto posting |  
  |   | 2024-09-16T11:05:00.004Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T11:05:00.164Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T11:05:00.164Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T11:05:01.069Z INFO: 59.98218333333333 minutes until the next auto-posting |  
  |   | 2024-09-16T12:05:00.011Z INFO: Starting auto posting |  
  |   | 2024-09-16T12:05:00.013Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T12:05:00.241Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T12:05:00.241Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T12:05:01.372Z INFO: 59.97715 minutes until the next auto-posting |  
  |   | 2024-09-16T13:05:00.019Z INFO: Starting auto posting |  
  |   | 2024-09-16T13:05:00.020Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T13:05:00.181Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T13:05:00.181Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T13:05:01.160Z INFO: 59.98066666666667 minutes until the next auto-posting |  
  |   | 2024-09-16T14:05:00.026Z INFO: Starting auto posting |  
  |   | 2024-09-16T14:05:00.027Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T14:05:00.224Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T14:05:00.224Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T14:05:01.297Z INFO: 59.97838333333333 minutes until the next auto-posting |  
  |   | 2024-09-16T15:05:00.035Z INFO: Starting auto posting |  
  |   | 2024-09-16T15:05:00.036Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T15:05:00.188Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T15:05:00.188Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T15:05:01.102Z INFO: 59.981633333333335 minutes until the next auto-posting |  
  |   | 2024-09-16T16:05:00.027Z INFO: Starting auto posting |  
  |   | 2024-09-16T16:05:00.028Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T16:05:00.197Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T16:05:00.197Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T16:05:01.285Z INFO: 59.97858333333333 minutes until the next auto-posting |  
  |   | 2024-09-16T17:05:00.037Z INFO: Starting auto posting |  
  |   | 2024-09-16T17:05:00.038Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T17:05:00.233Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T17:05:00.233Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T17:05:01.282Z INFO: 59.97863333333333 minutes until the next auto-posting |  
  |   | 2024-09-16T18:05:00.002Z INFO: Starting auto posting |  
  |   | 2024-09-16T18:05:00.003Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T18:05:00.205Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T18:05:00.205Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T18:05:01.257Z INFO: 59.97905 minutes until the next auto-posting |  
  |   | 2024-09-16T19:05:00.035Z INFO: Starting auto posting |  
  |   | 2024-09-16T19:05:00.036Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T19:05:00.235Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T19:05:00.235Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T19:05:01.205Z INFO: 59.97991666666667 minutes until the next auto-posting |  
  |   | 2024-09-16T20:05:00.003Z INFO: Starting auto posting |  
  |   | 2024-09-16T20:05:00.004Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T20:05:00.183Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T20:05:00.183Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T20:05:01.135Z INFO: 59.98108333333333 minutes until the next auto-posting |  
  |   | 2024-09-16T21:05:00.013Z INFO: Starting auto posting |  
  |   | 2024-09-16T21:05:00.014Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T21:05:00.208Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T21:05:00.208Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T21:05:02.600Z INFO: 59.95666666666667 minutes until the next auto-posting |  
  |   | 2024-09-16T22:05:00.000Z INFO: Starting auto posting |  
  |   | 2024-09-16T22:05:00.001Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T22:05:00.203Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T22:05:00.203Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T22:05:02.879Z INFO: 59.952016666666665 minutes until the next auto-posting |  
  |   | 2024-09-16T23:05:00.011Z INFO: Starting auto posting |  
  |   | 2024-09-16T23:05:00.012Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-16T23:05:00.216Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-16T23:05:00.216Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-16T23:05:01.365Z INFO: 59.977250000000005 minutes until the next auto-posting |  
  |   | 2024-09-17T00:05:00.007Z INFO: Starting auto posting |  
  |   | 2024-09-17T00:05:00.008Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T00:05:00.165Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T00:05:00.165Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T00:05:01.303Z INFO: 59.97828333333334 minutes until the next auto-posting |  
  |   | 2024-09-17T01:05:00.003Z INFO: Starting auto posting |  
  |   | 2024-09-17T01:05:00.004Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T01:05:00.198Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T01:05:00.198Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T01:05:01.322Z INFO: 59.97796666666667 minutes until the next auto-posting |  
  |   | 2024-09-17T02:05:00.015Z INFO: Starting auto posting |  
  |   | 2024-09-17T02:05:00.016Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T02:05:00.183Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T02:05:00.184Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T02:05:01.146Z INFO: 59.9809 minutes until the next auto-posting |  
  |   | 2024-09-17T03:05:00.035Z INFO: Starting auto posting |  
  |   | 2024-09-17T03:05:00.036Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T03:05:00.211Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T03:05:00.211Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T03:05:01.395Z INFO: 59.97675 minutes until the next auto-posting |  
  |   | 2024-09-17T04:05:00.007Z INFO: Starting auto posting |  
  |   | 2024-09-17T04:05:00.008Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T04:05:00.172Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T04:05:00.172Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T04:05:01.125Z INFO: 59.98125 minutes until the next auto-posting |  
  |   | 2024-09-17T05:05:00.025Z INFO: Starting auto posting |  
  |   | 2024-09-17T05:05:00.025Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T05:05:00.247Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T05:05:00.247Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T05:05:01.260Z INFO: 59.979 minutes until the next auto-posting |  
  |   | 2024-09-17T06:05:00.027Z INFO: Starting auto posting |  
  |   | 2024-09-17T06:05:00.028Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T06:05:00.192Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T06:05:00.192Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T06:05:02.247Z INFO: 59.96255 minutes until the next auto-posting |  
  |   | 2024-09-17T07:05:00.011Z INFO: Starting auto posting |  
  |   | 2024-09-17T07:05:00.012Z INFO: Posting testing with product team to 1253667918428897343 |  
  |   | 2024-09-17T07:05:00.166Z ERROR: Channel 1253667918428897343 cannot found |  
  |   | 2024-09-17T07:05:00.167Z INFO: Posting Protocol Governance AMA feedback to 1280888811798270054 |  
  |   | 2024-09-17T07:05:01.570Z INFO: 59.97383333333333 minutes until the next auto-posting

**Comment by berkingurcan** [comment]
Okay, I found the problem: https://github.com/MinaFoundation/PGT_gptSurveySummarizer/blob/main/src/lib/startAutoPosting.js#L52C1-L52C54

It deletes only messages starts with ballot box. I am changing the code.

**Comment by berkingurcan** [comment]
Solved with https://github.com/MinaFoundation/PGT_gptSurveySummarizer/pull/76

**Comment by CristinaEche** [comment]
@berkingurcan 

Here is the summary on the staging environment, it is working properly, however, the UI is different from the production environment, can you please check the versions and standardize both summaries, we would like to have the same UI in both environments

Staging:

<img width="856" alt="image" src="https://github.com/user-attachments/assets/c3274688-fb3b-4af4-96c2-83852c37f3b6">


Production:

<img width="856" alt="image" src="https://github.com/user-attachments/assets/1671b712-85b4-4f38-8310-396bb49a1b04">

<img width="856" alt="image" src="https://github.com/user-attachments/assets/ec86f14d-9293-44aa-a2ef-44f00cf9628a">

**Comment by CristinaEche** [comment]
@berkingurcan 

I ran an auto-post survey summary on both staging and production environments. Everything is now working properly on both. UI is now standardized:

**Production:**

<img width="987" alt="image" src="https://github.com/user-attachments/assets/e63c67ce-7046-4999-9a4d-0b7b22e43689">


**Staging:**

<img width="857" alt="image" src="https://github.com/user-attachments/assets/5f531a7b-a8c0-42b5-a7f2-f7d2e49b042f">

**Comment by berkingurcan** [comment]
opened again to fix it

**Comment by berkingurcan** [comment]
https://github.com/MinaFoundation/PGT_gptSurveySummarizer/pull/80 closed

**Comment by CristinaEche** [comment]
Issue remains unsolved:

Production environment still presenting issues when summarizing is leaving a trail of unerase messages instead of overwriting the summaries

**Comment by berkingurcan** [comment]
Okay I still know the problem and I will fix it today permanently.
